{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kizashi.fullname" $root }}-{{ $name }}
  labels:
    {{- include "kizashi.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    {{- include "kizashi.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port | default 8080 }}
      targetPort: http
      protocol: TCP
    {{- range $svc.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
    {{- end }}
---
{{- end }}
